package pl.polsl.lab1.oliwier.gebczynski.myfirstmvp.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import pl.polsl.lab1.oliwier.gebczynski.myfirstmvp.controller.GameController;

/**
 * A panel that provides the start screen of the Snake game.
 * It contains a text field for entering the player's name and a "START" button to begin the game.
 * It also listens for key events and provides an easy way to start the game using keyboard shortcuts.
 *
 * The user must enter their name in the text field to start the game. If the name is not entered,
 * an error message will be displayed.
 *
 * @author Oliwier Gebczynski
 * @version 1.1
 */
public class StartPanel extends JPanel {
    private JTextField nameField;
    private GameController controller;

    static Font TitleFont = new Font("Arial", Font.PLAIN, 100);
    static Font ButtonFont = new Font("Arial", Font.PLAIN, 40);
    static Font LabelFont = new Font("Arial", Font.PLAIN, 30);

    /**
     * Constructs the StartPanel and sets up the UI components.
     *
     * @param controller the GameController that will manage the game flow
     */
    public StartPanel(GameController controller) {
        this.controller = controller;

        setLayout(null);
        setBackground(Color.BLACK);

        // Title
        JLabel title = new JLabel("SNAKE");
        title.setFont(TitleFont);
        title.setForeground(Color.WHITE);
        title.setBounds(330, 100, 400, 100);
        add(title);

        // Input label
        JLabel setNameLabel = new JLabel("SET NAME: ");
        setNameLabel.setFont(LabelFont);
        setNameLabel.setForeground(Color.WHITE);
        setNameLabel.setBounds(390, 200, 400, 100);
        add(setNameLabel);

        // Text field
        nameField = new JTextField();
        nameField.setFont(LabelFont);
        nameField.setToolTipText("Enter the name");
        nameField.setBounds(300, 400, 400, 75);
        add(nameField);

        // Button
        JButton startButton = new JButton("START");
        startButton.setFont(ButtonFont);
        startButton.setMnemonic(KeyEvent.VK_S);
        startButton.setBounds(350, 700, 300, 100);
        add(startButton);

        startButton.addActionListener(new ActionListener() {
            /**
             * Handles the action performed when the start button is clicked.
             * Checks if the player has entered a name and starts the game if valid.
             *
             * @param e the ActionEvent generated by clicking the start button
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String playerName = nameField.getText();
                if (playerName.isEmpty()) {
                    JOptionPane.showMessageDialog(StartPanel.this, "Please enter your name to start the game.");
                    return;
                }

                controller.startGame();
            }
        });

        InputMap inputMap = startButton.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = startButton.getActionMap();

        inputMap.put(KeyStroke.getKeyStroke("control S"), "startAction");

        actionMap.put("startAction", new AbstractAction() {
            /**
             * This method is triggered when the keyboard shortcut (Ctrl + S) is pressed.
             * It simulates a click on the start button to start the game.
             *
             * @param e the ActionEvent generated by the keyboard shortcut
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                startButton.doClick();
            }
        });
    }
}
