-- zadanie 1 Dla każdego pracownika odpowiedzialnego za jakiś przedmiot podaj liczbę przedmiotów z których prowadzi zajęcia (tabela ROZKLADY).
SELECT ROZKLADY.NR_PRAC, PRACOWNICY.NAZWISKO, COUNT(DISTINCT ROZKLADY.NR_PRZEDM) AS LiczbaPrzedmiotow
FROM ROZKLADY
JOIN PRACOWNICY ON ROZKLADY.NR_PRAC = PRACOWNICY.NR_PRAC
JOIN PRZEDMIOTY ON PRACOWNICY.NR_PRAC = PRZEDMIOTY.NR_ODP_PRAC
GROUP BY ROZKLADY.NR_PRAC, PRACOWNICY.NAZWISKO;

-- zadanie 2 Podaj nazwiska i średnią ocen z przedmiotu ALGEBRA tych studentów, którzy z tego przedmiotu mają więcej niż jedną ocenę.
SELECT STUDENCI.NAZWISKO, AVG(OCENY.OCENA)
FROM STUDENCI
JOIN OCENY ON STUDENCI.NR_STUD = OCENY.NR_STUD 
JOIN PRZEDMIOTY ON OCENY.NR_PRZEDM = PRZEDMIOTY.NR_PRZEDM
WHERE PRZEDMIOTY.NAZWA_PRZEDM = 'ALGEBRA'
GROUP BY STUDENCI.NR_STUD, STUDENCI.NAZWISKO
HAVING COUNT(OCENY.OCENA) > 1

-- zadanie 3 Podaj przedmioty realizowane przez największą liczbę pracowników.
SELECT PRZEDMIOTY.NR_PRZEDM, PRZEDMIOTY.NAZWA_PRZEDM
FROM ROZKLADY
JOIN PRACOWNICY ON ROZKLADY.NR_PRAC = PRACOWNICY.NR_PRAC
JOIN PRZEDMIOTY ON ROZKLADY.NR_PRZEDM = PRZEDMIOTY.NR_PRZEDM
GROUP BY PRZEDMIOTY.NR_PRZEDM, PRZEDMIOTY.NAZWA_PRZEDM 
HAVING COUNT(DISTINCT ROZKLADY.NR_PRAC) >= ALL(SELECT COUNT(DISTINCT ROZKLADY.NR_PRAC) FROM ROZKLADY GROUP BY ROZKLADY.NR_PRZEDM)

-- zadanie 4 Podaj numery i nazwiska pracowników, którzy w temacie DYSK otrzymali wypłatę mniejszą od co najmniej jednej z wypłat pracownika o nazwisku GRZYBEK w dowolnym temacie.
SELECT DISTINCT PRACOWNICY.NR_PRAC, PRACOWNICY.NAZWISKO
FROM WYPLATY
JOIN PRACOWNICY ON WYPLATY.NR_PRAC = PRACOWNICY.NR_PRAC
JOIN TEMATY ON WYPLATY.NR_TEM = TEMATY.NR_TEM 
WHERE TEMATY.TEMAT = 'DYSK'
GROUP BY PRACOWNICY.NR_PRAC, PRACOWNICY.NAZWISKO, WYPLATY.KWOTA
HAVING WYPLATY.KWOTA < ANY(SELECT WYPLATY.KWOTA FROM WYPLATY JOIN PRACOWNICY ON WYPLATY.NR_PRAC = PRACOWNICY.NR_PRAC WHERE PRACOWNICY.NAZWISKO = 'GRZYBEK' GROUP BY WYPLATY.KWOTA)

-- zadanie 5 Podaj numery, nazwiska i daty urodzenia mężczyzn zatrudnionych w zespole OPROGRAMOWANIE, którzy są młodsi od każdego pracownika zespołu BUDOWA
SELECT DISTINCT PRACOWNICY.NR_PRAC, PRACOWNICY.NAZWISKO, PRACOWNICY.DATA_UR
FROM PRACOWNICY
JOIN ZESPOLY ON PRACOWNICY.NR_ZESP = ZESPOLY.NR_ZESP
WHERE ZESPOLY.NAZWA_ZESP = 'OPROGRAMOWANIE'
GROUP BY PRACOWNICY.NR_PRAC, PRACOWNICY.NAZWISKO, PRACOWNICY.DATA_UR
HAVING PRACOWNICY.DATA_UR > ALL(SELECT MAX(PRACOWNICY.DATA_UR) FROM PRACOWNICY JOIN ZESPOLY ON PRACOWNICY.NR_ZESP = ZESPOLY.NR_ZESP WHERE ZESPOLY.NAZWA_ZESP = 'BUDOWA' GROUP BY PRACOWNICY.DATA_UR)

-- zadanie 6 Podaj nazwiska najstarszych studentów na poszczególnych kierunkach
SELECT KIERUNKI.NR_KIER, STUDENCI.NAZWISKO, KIERUNKI.NAZWA_KIER, STUDENCI.NR_STUD
FROM STUDENCI
JOIN KIERUNKI ON STUDENCI.NR_KIER = KIERUNKI.NR_KIER
GROUP BY STUDENCI.NR_KIER, STUDENCI.DATA_UR, STUDENCI.NAZWISKO, STUDENCI.NR_STUD, KIERUNKI.NAZWA_KIER, KIERUNKI.NR_KIER
HAVING STUDENCI.DATA_UR = ANY(SELECT MIN(STUDENCI.DATA_UR) FROM STUDENCI GROUP BY STUDENCI.NR_KIER);